version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visualizadormedicos
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_visualizador
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dnaplus_web_magdalena
      MYSQL_USER: dnaplus
      MYSQL_PASSWORD: R@moid2512
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
